# Generated by Django 3.1.5 on 2021-01-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20210106_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speedups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('training_1m', models.IntegerField(default=0)),
                ('training_5m', models.IntegerField(default=0)),
                ('training_1h', models.IntegerField(default=0)),
                ('healing_1m', models.IntegerField(default=0)),
                ('healing_5m', models.IntegerField(default=0)),
                ('healing_1h', models.IntegerField(default=0)),
                ('construction_1m', models.IntegerField(default=0)),
                ('construction_5m', models.IntegerField(default=0)),
                ('construction_1h', models.IntegerField(default=0)),
                ('research_1m', models.IntegerField(default=0)),
                ('research_5m', models.IntegerField(default=0)),
                ('research_1h', models.IntegerField(default=0)),
                ('generic_1m', models.IntegerField(default=0)),
                ('generic_5m', models.IntegerField(default=0)),
                ('generic_1h', models.IntegerField(default=0)),
                ('generic_3h', models.IntegerField(default=0)),
                ('generic_8h', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.account')),
            ],
            options={
                'unique_together': {('account', 'day')},
            },
        ),
    ]
